repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.3.0
    hooks:
      - id: sqlfluff-lint